debug: True
app_listen_ip: 0.0.0.0
app_port: 5000
web_url: http://localhost:8000
secret_key: 'w7bAyd&zpc#jPUc2Y6K%gbRtuF@M9Y^@'
storage_class: whisper.storage.local.local
storage_config:
    path: /tmp/whisper
