debug: True
app_listen_ip: 0.0.0.0
app_port: 5000
max_data_size_mb: 1
secret_key: 'w7bAyd&zpc#jPUc2Y6K%gbRtuF@M9Y^@'
storage_clean_interval: 900

# storage_class: whisper.storage.memory.memory
# storage_config: {}

# storage_class: whisper.storage.local.local
# storage_config:
#     path: /tmp/whisper

# storage_class: whisper.storage.aws.s3
# storage_config:
#     bucket_name: my-secret-bucket
#     bucket_path: secrets

# storage_class: whisper.storage.gcp.gcs
# storage_config:
#     gcp_project: my-project-name
#     bucket_name: my-secret-bucket
#     bucket_path: secrets
